repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.13.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - "eslint"
          - "@typescript-eslint/eslint-plugin"
          - eslint-plugin-import
          - eslint-config-prettier
        args:
          - "--fix"
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: pylint -sn
        language: system
        types: [python]

      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
        exclude: (__init__|setup|(docs?|examples?|tests?|utils?)/.*)\.py$
