[tool.isort]
line_length = 120
profile = "black"
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true
skip_gitignore = true

default_section = "THIRDPARTY"
src_paths = ["api/app"]

[tool.black]
line-length = 120
target-version = ['py38']

[tool.pydocstyle]
add_ignore = "D105,D107,D200,D413,D401"
add_select = "D213,D404"

[tool.pylint.master]
ignore-patterns = "test_.*?py"

[tool.pylint.format]
max-line-length = 120

[tool.pylint.message_control]
disable = [
    "invalid-name",
    "unsubscriptable-object",
    "too-many-instance-attributes",
    "unnecessary-lambda",
    "unspecified-encoding"
]