openapi: "3.0.0"

info:
  title: Packing Organizer API
  version: "1.0"

paths:
  /boxes:
    get:
      summary: List all boxes/ search for a box
      operationId: list_boxes
      x-openapi-router-controller: Controllers.boxes
      responses:
        200:
          description: List of Boxes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Box"
      parameters:
        - name: page_size
          description: The Size of the paged results
          in: query
          schema:
            type: integer
          required: false
        - name: page_number
          description: The page number of the results
          in: query
          schema:
            type: integer
          required: false
        - name: search
          description: The filter to search labels by
          in: query
          schema:
            type: string
          required: false
    post:
      summary: Add a new box
      operationId: add
      x-openapi-router-controller: Controllers.boxes
      responses:
        200:
          description: Box just created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Box"
      requestBody:
        description: Box to add
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Box"
  /boxes/{box_id}/label:
    get:
      summary: gets the label for the box
      operationId: get_label
      x-openapi-router-controller: Controllers.boxes
      responses:
        200:
          description: Label for box
          content:
            image/png:
              schema:
                type: string
                format: binary
      parameters:
        - name: box_id
          description: The Id of the box
          in: path
          schema:
            type: integer
          required: true
  /boxes/labels:
    get:
      summary: gets the labels for all the boxes
      operationId: get_labels
      x-openapi-router-controller: Controllers.boxes
      responses:
        200:
          description: Labels for all boxes
          content:
            application/pdf:
              schema:
                type: string
                format: binary
  /boxes/{box_id}:
    get:
      summary: gets an existing box
      operationId: get
      x-openapi-router-controller: Controllers.boxes
      responses:
        200:
          description: Box just updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Box"
      parameters:
        - name: box_id
          description: The Id of the box to get
          in: path
          schema:
            type: integer
          required: true

    put:
      summary: Updates an existing box
      operationId: update
      x-openapi-router-controller: Controllers.boxes
      responses:
        200:
          description: Box just updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Box"
      parameters:
        - name: box_id
          description: The Id of the box to update
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        description: Box To Update
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Box"

    delete:
      operationId: delete
      summary: Delete a box
      x-openapi-router-controller: Controllers.boxes
      responses:
        204:
          description: Box has been deleted
      parameters:
        - name: box_id
          description: The Id of the box to delete
          in: path
          schema:
            type: integer
          required: true

  /boxes/{box_id}/items:
    get:
      summary: List all boxes/ search for a box
      operationId: list_items
      x-openapi-router-controller: Controllers.boxes
      responses:
        200:
          description: List of Items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
      parameters:
        - name: box_id
          description: The Id of the box this item belongs to
          in: path
          schema:
            type: integer
          required: true
        - name: page_size
          description: The Size of the paged results
          in: query
          schema:
            type: integer
          required: false
        - name: page_number
          description: The page number of the results
          in: query
          schema:
            type: integer
          required: false
        - name: search
          description: The filter to search labels by
          in: query
          schema:
            type: string
          required: false
    post:
      summary: Add a new Item
      operationId: add_item
      x-openapi-router-controller: Controllers.boxes
      responses:
        200:
          description: Item just created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
      parameters:
        - name: box_id
          description: The Id of the box this item belongs to
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        description: Item to add
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
  /items/{item_id}:
    delete:
      operationId: item_delete
      summary: Delete an item
      x-openapi-router-controller: Controllers.items
      responses:
        204:
          description: Item has been deleted
      parameters:
        - name: item_id
          description: The Id of the item to delete
          in: path
          schema:
            type: integer
          required: true

components:
  schemas:
    Box:
      type: object
      required:
        - id
        - label
        - description
      properties:
        id:
          type: integer
          description: Unique identifier
          example: 123
          readOnly: true
        label:
          type: string
          description: Box Label
          example: Box 1
        description:
          type: string
          description: Short Description of Box
          example: Kitchen Stuffs
    Item:
      type: object
      required:
        - id
        - boxId
        - name
      properties:
        id:
          type: integer
          description: Unique identifier
          example: 123
          readOnly: true
        boxId:
          type: integer
          description: Box Id
          example: 123
        name:
          type: string
          description: Description of Item
          example: Forks
