name: Pull Request Validation

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: "**/requirements*.txt"

      - name: Install dependencies
        run: |
          pip install -r api/requirements.dev.txt > /dev/null

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Install Dependencies
        working-directory: ui
        run: |
          npm ci

      - name: Linting and formatting
        run: |
          pre-commit run --all-files

      - name: Build Angular
        working-directory: ui
        run: |
          npm run build
